name: Sync Fork

on:
  schedule:
    # Runs every Sunday at 00:30 UTC
    - cron: "30 0 * * 0"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your fork's repository
      - name: Checkout fork repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history to allow merges

      # Step 2: Add the upstream repository and fetch its latest changes
      - name: Set up upstream
        run: |
          git remote add upstream https://github.com/is-a-dev/register.git
          git fetch upstream

      # Step 3: Merge upstream changes into your fork's main branch
      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit

      # Step 4: Push the changes to your fork's main branch
      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses GitHub Actions' automatic token
